.TH ORG-RUBY "1" "March 2013" "org-ruby 0.8.1" "User Commands"
.SH NAME
org-ruby \- TODO
.SH SYNOPSIS
.B org-ruby
\fI<file> \fR[\fIoptions\fR]
.SH DESCRIPTION
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this message
.TP
\fB\-d\fR, \fB\-\-debug\fR
Run with $DEBUG true
.TP
\fB\-t\fR, \fB\-\-translate\fR FORMAT
Translate the ORG file to the specified format.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version
.SH EXAMPLES
TODO
